### ISSUE TITLE
请问为什么无论源码安装还是pip安装，vscode中都无法自动补全

### ISSUE THREAD

**Issue by czhou** [qingstor/qingstor-sdk-python#61]
No name 'sdk' in module 'qingstor'pylint(no-name-in-module)

**Comment by czhou** [comment]
在sdk目录下新建一个__init__.py空文件解决了...

**Comment by Xuanwo** [comment]
https://github.com/qingstor/qingstor-sdk-python/tree/master/qingstor/sdk

但是我们 SDK 下面是有这个文件的

**Comment by czhou** [comment]
是的 我前几天重新安装的时候__init__.py又出来了
但是之前确实没有 很奇怪
