### ISSUE TITLE
分段上传如何合并的问题

### ISSUE THREAD

**Issue by SunMinghui19** [qingstor/qingstor-sdk-python#96]
第一、我参照该文件 qingstor-sdk-python/docs/example/multipart_upload.md ，想要使用qingstor的文件分段上传功能，当文件分段上传完成后，该文档最后的部分给出了fin_resp，这是一个从未出现的参数

第二，参考上下问的描述，我使用了如下方法尝试合并文件
with open(filepath, 'rb' ) as f:
   for i in range(parts_count):
       start = time.time()
       part_size = min(chunk_size, file_size - i * chunk_size)
       data = f.read(part_size)
       part_resp = bucket_srv.upload_multipart(object_key,upload_id=upload_id,part_number=str(i), body=data)
       end = time.time()
       elasped = end -start
       print(end-start)
       print(elasped*(parts_count-i))
       if part_resp.status_code != 201:
          print("Upload part of object(name:{}) to bucket({}) failed with given message:{}".format(object_key,bucket_name,str(part_resp.content,'utf-8')))
          abort_resp = bucket_srv.abort_multipart_upload(object_key,upload_id)
          print("Abort multi upload executed: 204 expected, actually:%d", abort_resp.status_code)
       else:
          print("part %d uploaded." %i)
list_resp = bucket_srv.list_multipart(object_key=object_key, upload_id=upload_id)
final_resp = bucket_srv.complete_multipart_upload(object_key=object_key,upload_id=upload_id)

但得到了下面的错误
  File "qstor_upload.py", line 57, in <module>
    final_resp = bucket_srv.complete_multipart_upload(object_key=object_key,upload_id=upload_id)
  File "/usr/local/python3/lib/python3.8/site-packages/qingstor_sdk-2.6.0-py3.8.egg/qingstor/sdk/service/bucket.py", line 1210, in complete_multipart_upload
  File "/usr/local/python3/lib/python3.8/site-packages/qingstor_sdk-2.6.0-py3.8.egg/qingstor/sdk/service/bucket.py", line 1197, in complete_multipart_upload_request
  File "/usr/local/python3/lib/python3.8/site-packages/qingstor_sdk-2.6.0-py3.8.egg/qingstor/sdk/service/bucket.py", line 1233, in complete_multipart_upload_validate
TypeError: 'NoneType' object is not iterable

**Comment by frostyplanet** [comment]
abort_multipart_upload 取消了之前传的分段, 后面合并 complete 就失败了.

**Comment by frostyplanet** [comment]
complete 还要传要合并的 part number 列表, 请参考 api 文档,
